### ISSUE TITLE
Local dependency on geometry3Sharp

### ISSUE THREAD

**Issue by lundmikkel** [gradientspace/gsGCode#2]
The csproj file contains a reference to a local version of geometry3Sharp:

``` xml
<ItemGroup>
    <ProjectReference Include="..\geometry3Sharp\geometry3Sharp.csproj">
      <Project>{0c518dda-28fe-44ca-9ab0-f9773974f13a}</Project>
      <Name>geometry3Sharp</Name>
    </ProjectReference>
</ItemGroup>
```

You might want to replace that.

**Comment by rms80** [comment]
replace it how? gsGCode depends on the g3sharp library...

**Comment by lundmikkel** [comment]
That might very well be true, but now you have to download both solutions to get this one to work. You could build geometry3Sharp and copy the dll to this project, and reference the dll instead. That way you wouldn't have to download both of them.

And just to nitpick: your readme says this project has no dependencies, which then isn't really true.

**Comment by rms80** [comment]
updated comment in readme.
